### ISSUE TITLE
Fails to build with pyinstaller 3.2 and python 2.7

### ISSUE THREAD

**Issue by gamerman315** [genotrance/px#1]
Looking into the issue it appears px.py failes to compile under python 2.7. The documentation didn't state which version of python was needed to build the application.

**Comment by genotrance** [comment]
I'll look into porting Px to Python 2.7.

Meanwhile, it works fine with Python 3.5, I used the Miniconda distro. I'll update the documentation accordingly.

**Comment by genotrance** [comment]
Just checked in changes to allow Px to run on Python 2.7. The limitation is that it will only run in a single process since the ability to share sockets across processes on Windows was only added in Python 3.3 - the socket.share() and socket.fromshare() methods. I've noted this in the README.

I tried using multiprocessing.reduction to pickle the socket but unpickling requires socket.fromfd() which is Linux only. As such, Px on Python 2.7 is still multithreaded so it is definitely usable but struggles when you have multiple parallel connections.

I've not posted new binaries since there's no real change in functionality or behavior. Meanwhile, I'll close this issue once you have had some time to evaluate.

**Comment by gamerman315** [comment]
Awesome, can confirm it is now building for Python 2.7. Thanks for the great work!
