### ISSUE TITLE
Exit automatically if log = 0

### ISSUE THREAD

**Issue by pffang** [genotrance/px#165]
Px-proxy version 0.8.3 can only work with log = 1 on my Windows 10 PC.
If log = 0, px-proxy will exit automatically in several minutes.

**Comment by genotrance** [comment]
How is px installed? Is it the compiled binary, installed via pip or run directly with Python?

Also, does it work for some time, responding to incoming connections and then quit, or quit during startup? Does it quit for a specific site or url or is it completely random?

It seems like there's an error occurring that isn't being caught. It's hard to tell since it could be happening anywhere and lots of code has changed recently.

If you can reproduce it consistently, we could narrow it down by trying older versions until it stops happening but that might be a bunch of testing.

**Comment by pffang** [comment]
Just extract from px-v0.8.3-windows.zip and run px.exe.

It can work fine for a while after its startup. But then the process disappear from task manager.

I think it's not related to specific site or URL. Even I don't connect any client to it, it still quits automatically after several minutes.

Because log is disabled, I cannot get any useful information.
This issue always happen in my side, maybe you can have a try with package px-v0.8.3-windows.zip and 'log = 0' in your side.

**Comment by genotrance** [comment]
I tried this on my test systems and Px ran for the whole day with no issues. There's obviously something happening but checking the code and testing didn't give me any ideas.

Does it also crash eventually with debug? Are you sure there's nothing using Px through this time?

I agree it's super hard to tell what's happening here without debug. Perhaps you can try `pythonw px.py` instead of the Px binary and see if you can find some more info.

**Comment by pffang** [comment]
Sorry for late reply.
About two months ago, I compiled a version base on master branch, it works fine.
New version 0.8.4 also works fine now. 
I think we can close this issue.
