### ISSUE TITLE
No --help output in shimed .exe (Chocolatey)

### ISSUE THREAD

**Issue by ccbur** [genotrance/px#26]
I'm currently building an internal Chocolatey environment. During creation of a px-0.3.0 package I realized that I cannot see any ouput from my shimed px.exe. Shiming is the chocolated way of putting installed programs in the PATH. To avoid cluttering of the PATH a new small .exe-File with the same name (px.exe) is generated at a location within the PATH. This exe redirects any console input/output to the original installed application outside of the PATH. Normally this works quite well, but not for px.

I think the reason is  how attachConsole works!? It looks for an parant cmd/cmd.exe and attaches to this console. It will never find a parent powershell.exe, git-cmd.exe or the shimed px.exe. 

Maybe the first parsecli()-Call should stick to the old fashioned way of using the console!?

**Comment by genotrance** [comment]
So Px is actually an application that is designed to run in the background. It is compiled as a window-less app so there's no console window by default. If it were built as a console app, it would pop up a console window and sit there. Even if you hide that, it would pop up and then get hidden and isn't the best service app experience.

Given there's useful console output, I use the AttachConsole() method to write to a console if one exists. I've posted an updated test build that also binds to a Powershell parent console. Meanwhile, git-cmd uses cmd already so it works as is. Even if you run Px with your method, it should find the parent console and write to it since it recurses till it finds a console parent. If you run Px directly from Explorer though, it won't find a parent console and skip writing to stdout.

The behavior in Powershell isn't [ideal](https://stackoverflow.com/questions/48315447/c-sharp-app-command-line-output-written-to-input-line) but better than nothing.

That being said, can you please try out this new px.exe and let me know if it works with your shimed exe? I'm assuming you were running it in Powershell. If not, can you please run px with --debug to see what comes out in the log file?

**Comment by ccbur** [comment]
Ah, I see. Sorry, I'm used to linux environments and I'm alway wondering about those kind of (windows) problems :)

Directly in Powershell works now, but not the shimed px.exe, neither from cmd.exe, nor powershell.exe. Debug log is

_MainProcess: MainThread: 1519285657: attachConsole: No parent console to attach to_

I changed the `attachConsole()`-Method to connect to the shimed px.exe, but 
`ctypes.windll.kernel32.AttachConsole()`
just throws an error :-( And there is no cmd.exe or powershell.exe in thie hierarchie. It's just the shimed px.exe.

So no console output possible... I guess I have to live with that.

**Comment by genotrance** [comment]
How are you running this shimed executable? If you are running it from Explorer or Start->run, there's no command console that's the owning parent. It would only work if you ran the shimed executable from a cmd or powershell console since Px would find it as it looked through the parent processes. What does the process hierarchy look like in Process Explorer?

Can you show me how to build/install via Chocolatey? I can try it out.

**Comment by ccbur** [comment]
Yes, I'm running the shimed exe from cmd or powershell, but neither works.

Is there a way to send you my nupkg directly? Github is not accepting this file via the upload function. I tried to rename it to .zip, tried to rewrap it in a zip, tried every trick there might be, but Github is still not accepting this upload from me :-(

With the nupkg you just need to install Chocolatey (see [install](https://chocolatey.org/install)), reopen a cmd.exe or powershell.exe and then install the nupkg with

_cd "c:\path_to_folder_with_pxnupkg"
choco install px -s "'.;https://chocolatey.org/api/v2/'"_

After this the shimed px.exe should be in your path and the original should be here: C:\ProgramData\chocolatey\lib\px\tools\px-v0.3.0\

**Comment by ccbur** [comment]
And here a screenshot from ProcessExplorer:

![pxprocexp](https://user-images.githubusercontent.com/33153172/36593518-dcb22e36-1891-11e8-9240-2ee49fbee930.PNG)

As you can see, no cmd.exe in the hierarchy. But I started it from a running cmd.exe :-/

**Comment by genotrance** [comment]
Could you send the spec file? I presume I can build the pkg without Visual Studio. If not, you could send it over @ https://send.firefox.com

**Comment by ccbur** [comment]
Here the full nupkg based on the current pre-release:
https://send.firefox.com/download/25db50ec09/#Zigr3Q1D_7NhKy8BE4WOtg

You can build this with chocolatey directly via [choco pack](https://github.com/chocolatey/choco/wiki/CommandsPack).

But I'm currently struggling with the latest pre-release. I'm not able to get any NTLM authentication any more... :-( Maybe it's Kerberos-related or I messed something up.

**Comment by genotrance** [comment]
Can you also please send me the spec file? I presume that's what you need for choco pack? I'll try the pkg until then.

**Comment by genotrance** [comment]
Okay, found the spec file once I installed, never mind.

**Comment by genotrance** [comment]
So the shimgen process checks and generates a shim based on type of EXE. Since Px.exe is a GUI app, it generates a GUI shim and the default behavior for GUI shims is to exit once the app has been started. Because of this, Px no longer has a parent or a way to figure out which console it was run from.

Shims do have a ```--shimgen-waitforexit``` flag which allows them to wait until child is done. I ran ```px --shimgen-waitforexit --help``` and the output works as expected. I don't see a way for Chocolatey to setup a GUI shim with wait for exit set by default though.

I'm also wondering if wait for exit should be always true. If it is, you will always have a console popup even if you don't run from a console which was the whole reason for creating Px as a GUI app.

An option is to force Px to create a console if run with --foreground and to set --foreground if --help is specified or some such thing. Problem though will be that a separate console will popup with the help output and promptly exit too, never showing it's output.

I'm not sure what the solution is at this point since Px isn't really doing something standard - GUI app writing to parent console if one exists.

**Comment by genotrance** [comment]
Assuming shimgen is updated as suggested [here](https://github.com/chocolatey/shimgen/issues/42#issuecomment-369793128), Px will start working as expected. I'm not sure if we should keep this issue open though.

**Comment by ccbur** [comment]
You're right. Let's hope for an improvement there. 

I'll close this issue.
