### ISSUE TITLE
Certificates

### ISSUE THREAD

**Issue by OttoDiesel** [genotrance/px#42]
It seems that px, cntlm and ntlmaps don't work when the requested URL is HTTPS and has a certificate.
If in IntelliJ IDEA I set the proxy to the one of px and want to update IntelliJ then IntelliJ displays a window with the details of the certificate which I can then accept. But other tools for which I used px don't display any window with the certificate but an error message, like ConEmu. There should be a solution for this in px. The easiest would be an option to trust all certificates. I am no expert, I hope you understand what the problem is and can provide a solution.

**Comment by genotrance** [comment]
I don't think px or the other proxies have anything to do with certificates. When it comes to https sites, all px (and the other proxies) do is make a HTTP tunnel to the remote server and pass packets back and forth. 

This is because the browser has to trust the end server so all SSL transactions happen between those two entities. All proxies just see SSL traffic going back and forth which is essentially garbage to them.

**Comment by OttoDiesel** [comment]
But you see the problem? And what is a solution then if you reject just what I wrote?

I can't use tools like px for a proxy in a tool like ConEmu. If px would be written in Java I could debug it with my knowledge and implement to trust all certificates, but this way I have no chance. I tried to solve it with Java but I just don't know enough of this NTLM stuff to make it working with Apache libraries.

**Comment by OttoDiesel** [comment]
In the previous company, which also had a corporate proxy, ntlm worked (and probably px would have worked there too). Both companies use Windows 7 for the employee desktop. Maybe the new company for which I work uses another product for the corporate proxy or has some other configuration.

ConEmu and most other tools are not capable to handle the certificate in this case obviously. IntelliJ is capable by showing a popup to the user once,  so that I can decide whether to trust that certificate.

I can try to provide more information to make it reproducible. I see that it might be hard to reproduce it, it could be a tiny setting somewhere in the system causing this behavior.

**Comment by ccbur** [comment]
Is the proxy in your new company terminating your ssl connection and de/reencrypting your connection? Therefore you would need to trusts the used root certificate (of this proxy) in all of your applications. Or configure the application to ignore the wrong certificate. If this is not possible, too bad, because that's exactly the idea of using SSL/TLS: Trust the connection, that no man in the middle is tempering with your data (cp. [https://en.wikipedia.org/wiki/Proxy_server#Filtering_of_encrypted_data](https://en.wikipedia.org/wiki/Proxy_server#Filtering_of_encrypted_data)).

Thank goodness I've no experience with those kind of proxies / companies. :-)

Nevertheless, there is nothing px could do about this, because it's not involved.

**Comment by OttoDiesel** [comment]
I will check if I can do this and if it solves it, thank you for this idea. I am not sure what the proxy actually does. I can get the HTTPS URLs by using Internet Explorer with exactly that proxy, for instance get through to the ConEmu update site with Internet Explorer which uses the corporate proxy but not by using px configured with the same corporate proxy from ConEmu. I think the proxy product is called Bluecoat.

**Comment by ccbur** [comment]
At least I can find some hints in this direction: [https://security.stackexchange.com/questions/33976/man-in-the-middle-blue-coat-proxy-ssl-or-what](https://security.stackexchange.com/questions/33976/man-in-the-middle-blue-coat-proxy-ssl-or-what)

**Comment by genotrance** [comment]
Are you saying that if you setup IE through px, you cannot get through to any https website? However, IntelliJ somehow can go through px?

**Comment by OttoDiesel** [comment]
Sorry for the late reply, I focused on something else and then was on holiday.
I don't remember that I setup IE through px. I can try that. I setup other tools which need a proxy, like ConEmu, and ConEmu could not get through its HTTPS update site.
But IntelliJ got through. It popped up a window displaying a certificate which I then could approve. Then it got through with px.
I am working in the financial industry, they seem to want to inspect network traffic with their Bluecoat thing and screw other things up with it. Of course they don't care about it as long as they feel secure with Bluecoat.

**Comment by genotrance** [comment]
It appears IntelliJ has the ability to talk SSL with Bluecoat to go through the proxy. Px really cannot do anything here since it talks pure HTTP with the proxy and all SSL happens between the application and end site. In this case, it is between the application and the Bluecoat proxy which then re-encrypts the traffic with a separate SSL transaction with the site.
