### ISSUE TITLE
Linux support :)

### ISSUE THREAD

**Issue by mduft** [genotrance/px#70]
It would be great to have this on Linux as well. We're using SSSD and Kerberos tickets on Linux to authenticate against our AD and have an NTLM proxy which requires the same authentication...

Any chance?

**Comment by genotrance** [comment]
I have it in mind but haven't gotten around to generalizing the code since I didn't see much interest here.

More thumbs up and feedback, or PRs will obviously prioritize this!

**Comment by koconder** [comment]
+1 Unix support should allow porting to Macintosh and help get rid of CNTLM which is crazy outdated and now dead

**Comment by marceliq** [comment]
+1

**Comment by jpvlerbe** [comment]
I would very much also love linux support.

**Comment by jpvlerbe** [comment]
> I have it in mind but haven't gotten around to generalizing the code since I didn't see much interest here.
> 
> More thumbs up and feedback, or PRs will obviously prioritize this!

Can you detail the issues that make it not run on Linux currently? With some support from you I might have a go add adding Linux support.

**Comment by superm1** [comment]
I would think that the biggest reason for Linux support would actually be to use under WSL.  Under WSL then you could potentially reach out to an NTLM proxy without needing to hardcode credentials.

**Comment by hippm** [comment]
+1

**Comment by Ruben-VV** [comment]
+1

**Comment by genotrance** [comment]
Note that there's no way to authenticate on Linux without credentials. There is no sspi. If Px does support Linux, it will require credentials just like cNTLM and the rest do.

**Comment by koconder** [comment]
@genotrance only other thing i could think of is Kerberos but yes it would need creds

**Comment by qichaozhao** [comment]
@genotrance and all, I started taking a look at this since it's something I need for work and I have a very very very bare bones version of it working for my specific use case (Negotiate authentication with Kerberos behind my corporate firewall), but without any multiprocessing.

Other functionality like auto proxy detection and using PAC files etc I just commented it out to get it working for my use case. I tested it on OSX & Windows Ubuntu.

The branch is here if anyone else may find it useful immediately: https://github.com/qichaozhao/px/tree/osx_linux_compat

But I also wanted to get your opinion @genotrance on how you think you might want to evolve the codebase going forwards, because currently the windows functionality is very entwined with the code and in the current format it's not very separable I think without it getting quite messy.

My personal opinion would be perhaps to do some refactoring wherein the core proxy server logic which I think are mainly the `Proxy` class and the `ThreadedTCPServer` class (and their supporting functions/classes) go into a core module as I think these are pretty much OS independent, and the rest of the application maybe gets separated out.

I can take a crack at that in the coming weeks and see where we end up if you think this is a good approach?

**Comment by genotrance** [comment]
@qichaozhao - I agree a project of this size should already have been split out into multiple files. It makes PRs and such features easier. Would you be able to make a more detailed proposal of how you would split it out?

**Comment by genotrance** [comment]
Okay, I spent some time to split it into multiple files. Check out the branch [here](https://github.com/genotrance/px/tree/split). Feedback appreciated.

**Comment by qichaozhao** [comment]
@genotrance awesome, I'll leave some detailed comments once I've had time to look (may take me a few days given my current workload).

Might I also suggest we make another issue for the refactor that blocks this issue to track the refactor discussion just to keep things easy and separate?

**Comment by fgimian** [comment]
The issue with cntlm for me is that it doesn't support PAC files.  That feature alone would give px an advantage for many of us faced with a company that has a relatively detailed PAC file like mine. :smile:

**Comment by genotrance** [comment]
I have been working on a Nim version of Px that leverages libcurl to handle proxy authentication. This gives us a portable binary that can auth through any proxy that libcurl supports. It is already working on Windows and Linux, and OSX support can be added with minimal effort. Further, since it is a using Nim, it is far more performant and easy to distribute (single binary).

Please check it out: https://github.com/genotrance/px2

There's no documentation or release binaries provided yet but I will appreciate any feedback on the approach.

As such, the Python based Px will continue to be available but all new efforts are focused on px2.

**Comment by segalion** [comment]
Hello. 
I want to comment my perspective about px and non-windows enviroments:

I think one of python progams problems inside corporation enviroment is the tipical NTLM proxy. Most of libraries and code miss this casuistic (i.e. O365 libraries, etc.).
The two great things of python for me are:
- Huge (and probabbly biggest) library
- great multiplatform (only desktop) support.

With this px (python code), people can over-pass the ntlm problem mantaining a pure python enviroment. I like to has px priimary as a pyhon module to include and work with it inside python programs. I could use cnltm, but I think it is just like a "bad portable & extendible" solution.

So this is why I think that could be great to have same python solution but having all "windows specific" as optional, so things could work equal in linux and OSX, just with a prompt for user/password/proxy instead of automagycally,

You could make your python program, using all libraries you want (O365, youtube, telegram, whatsap, bla bla bla .....), and just include 'px' requirement to make working your porgram inside a corporate NTLM enviroment (and working on linux/OSX and windows)....

**Comment by genotrance** [comment]
Happy to [announce](https://github.com/genotrance/px/discussions/136) that Linux is now supported! Looking forward to the issue reports and feedback.

Note that the px2 Nim experiment is dead and future work will focus on this Python version. Some good ideas did come out of it so you can expect some evolution here.
