### ISSUE TITLE
[Feature request] Choice of authentication mode

### ISSUE THREAD

**Issue by JeromeRF** [genotrance/px#73]
Hi genotrance,
My corporate firewall supports different authentication protocols and answers NTML before KERBEROS.
Because of that and the way the "do_proxy_table" function is implemented (if NTLM is supported choose NTLM then if KERBEROS is supported choose KERBEROS then if NEGOTIATE is supported choose NEGOTIATE) NTLM is choosed by px. But I would like to use Kerberos as there is no configuration at all in the configuration file (and no password stored in clear).
There may be a way to configure px to force Kerberos but I did not found it.
I made a quick and dirty patch by inverting the order of the choice in the "do_proxy_table" function and it works very well. But the patch can not be pushed this way as this order may have been carefully chosen.
Could it be possible to add a parameter in the px.ini file to force the choice of protocol (or the order of protocol detection).
Thanks very much.

**Comment by genotrance** [comment]
It appears there's a misunderstanding here. If you do choose NTLM, there is still no need to specify the password since Px uses pywin32 to do the auth automatically. Even if a password were required on systems which don't belong to the corporate network, the password is still stored in the Windows Credential Manager so there is no need for clear passwords.

Regardless, I have added support for picking Kerberos in the INI file if you so prefer.
