### ISSUE TITLE
should we send proxy-authorization header with each new request?

### ISSUE THREAD

**Issue by btsimonh** [genotrance/px#87]
In my (test) setup, with credential caching in Wingate - if (a thread of) px has authorized, it stores the proxy type, and adds a 'proxy-authorization' header to every subsequent request, which then results in a challenge etc.  Without this header, Wingate will honor the request without asking for authentication.
It's really hard to find good information; but I am wondering if we SHOULD send 'proxy-authorization' unsolicited, or if it should ONLY be sent in response to a 407?

i.e. is there any circumstance when the 'proxy-authorization' we send is valid for a subsequent request (e.g. contains a cookie, or some token)?

Illustrative logs attached:
logs-with-proxy-stored\ - logs of current version.
logs-with-proxy-None-every-request\ - logs with setting:
`            State.proxy_type[self.proxy_address] = None`
in do_proxy_type()

*logs-with-proxy-stored*
Note: the Main process never needs to authorize, because process_1 got there first.
But process_1 gets a 407 for *every* subsequent request (because of the `do_socket: Sending extra Proxy-Authorization: sanitized len(81)`, and so has to authenticate every time, when it does not need to.

*logs-with-proxy-None-every-request*
Note that both main and process1 DO authenticate (because they hit at the same time?), but once authenticated, they never need to do so again (until the IP based credentials time out).

[logs.zip](https://github.com/genotrance/px/files/3197571/logs.zip)

**Comment by genotrance** [comment]
This one seems non-trivial to fix. Start here: https://github.com/genotrance/px/blob/d196d2ad66e3b3ee84b429f54c7bb283562389c0/px.py#L701.

If proxy type is known, either due to previous check or if specified in INI file, response sent by `do_proxy_type()` is 407 which means `do_transaction()` will always send authorization string. Upstream proxy does have an option to not challenge and I have code for that case. My upstream proxy used to cache in the past but off late, seems I need to authorize every transaction. Could be due to heightened security these days.

If we assume upstream proxy caches, we will have an extra 407 round for every transaction before we send auth and then get challenged. If we figure out a clean way to avoid doing this every time, the upstream proxy could also clear cache or timeout our credentials and send a 407 again. Basically, the code needs to try without credentials and only auth when needed. However, I'm not sure if that is really optimal or not. Open to ideas.

**Comment by btsimonh** [comment]
I currently set the proxy type to null at start of do_proxy_type, so it always attempts without auth, and then only if 407 is returned, does it look for proxy type.
Works for me, but then that is only one of many proxy manufacturers, and not even my customer's proxy mfg.
I do have a header.
`do_socket: Received Proxy-Support: session-based-authentication`
but google does not reveal if this indicates anything; in fact it indicates this is probably not the droid we are looking for.....

The question is; is the auth string actually valid in this case, having not been asked for?  It is true that it results in a challenge directly, rather than a 407 with auth options, then a challenge....

**Comment by genotrance** [comment]
We are now using libcurl to deal with the proxy so hopefully this should no longer be an issue.

**Comment by btsimonh** [comment]
but no more single executable :(.
I'll check the new arrangement; my 'release' mechanism will change a lot.
Do we need everything in the windows zip?  or just the exe and the dlls?

**Comment by genotrance** [comment]
Reason I moved away from single file is #61 and many related complaints about the binary being treated as a virus. 

Most of the files are Python binaries, and a few other dependent dlls. You will likely need all of them.

**Comment by genotrance** [comment]
Ya that's the main reason the Nuitka build also is not a single file since it would do similar shenanigans. As much as I like a single file, once the app is setup, it doesn't really matter anyway if there's 20 other files next to it.

**Comment by btsimonh** [comment]
thanks again for px.  I used it last week to bounce my internet through a home machine from greece (with my personal VPN) to watch a UK TV service.
